# Generated by Django 3.1 on 2021-07-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='centroAt',
            field=models.CharField(choices=[('Hospital Honorio Delgado', 'Hospital Honorio Delgado'), ('Hospital Goyeneche', 'Hospital Goyeneche'), ('Clinica de Neuropsiquiatria y Salud Mental San Rafael', 'Clinica de Neuropsiquiatria y Salud Mental San Rafael'), ('Centro de Salud Mental Muñoz', 'Centro de Salud Mental Muñoz'), ('Centro de Salud Mental Comunitario Hunter', 'Centro de Salud Mental Comunitario Hunter'), ('El Instituto de Salud Mental Carlos Alberto Seguin Escobedo', 'El Instituto de Salud Mental Carlos Alberto Seguin Escobedo'), ('Centro de Adicciones Y Salud Mental', 'Centro de Adicciones Y Salud Mental'), ('Centro de salud mental comunitario San Martin de Porres Arequipa', 'Centro de salud mental comunitario San Martin de Porres Arequipa'), ('Clinica de Salud Mental y Adicciones', 'Clinica de Salud Mental y Adicciones'), ('Centro Psicologico Kid Zone', 'Centro Psicologico Kid Zone'), ('Centro de Salud Mental y Adicciones Victor Raul Hinojosa', 'Centro de Salud Mental y Adicciones Victor Raul Hinojosa'), ('Centro de Salud Mental Comunitario CAYMA', 'Centro de Salud Mental Comunitario CAYMA'), ('Psicologos Bienestar - Sede Arequipa', 'Psicologos Bienestar - Sede Arequipa'), ('Centro de Salud Mental Comunitario Simon Bolivar', 'Centro de Salud Mental Comunitario Simon Bolivar'), ('Centro Psicologico de la Fuente', 'Centro Psicologico de la Fuente'), ('Centro Psicologico', 'Centro Psicologico'), ('Psicomedic-Tratamiento Psiquiatricos', 'Psicomedic-Tratamiento Psiquiatricos'), ('Centro Psicologico - NEURO TALENTO', 'Centro Psicologico - NEURO TALENTO')], max_length=100),
        ),
    ]
