# Generated by Django 3.1 on 2021-08-02 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_auto_20210802_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
    ]
