# Generated by Django 3.1 on 2021-08-02 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComentariosHome',
            fields=[
                ('comHCod', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUserH', models.CharField(max_length=200)),
                ('comentarioH', models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(15)])),
            ],
        ),
    ]
