# Generated by Django 3.1 on 2021-07-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('ForCod', models.AutoField(primary_key=True, serialize=False)),
                ('Resp1', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp2', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp3', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp4', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp5', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp6', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp7', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp8', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp9', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp10', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp11', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp12', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp13', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp14', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp15', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp16', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp17', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp18', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
                ('Resp19', models.IntegerField(choices=[(0, 'No'), (1, 'Si')])),
            ],
        ),
    ]
