# Generated by Django 3.1 on 2021-07-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('ForCod', models.AutoField(primary_key=True, serialize=False)),
                ('Resp1', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp2', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp3', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp4', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp5', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp6', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp7', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp8', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp9', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp10', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp11', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp12', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp13', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp14', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp15', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp16', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp17', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp18', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
                ('Resp19', models.CharField(choices=[(0, 'No'), (1, 'Si')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
