# Generated by Django 3.1 on 2021-08-02 04:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_auto_20210704_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='Resp1',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp10',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp11',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp12',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp13',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp14',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp15',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp16',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp17',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp18',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp19',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp2',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp3',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp4',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp5',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp6',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp7',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp8',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='Resp9',
        ),
        migrations.AddField(
            model_name='formulario',
            name='pregunta',
            field=models.CharField(default='', max_length=120, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
    ]
