# Generated by Django 3.1 on 2021-08-02 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_auto_20210802_0401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formulario',
            new_name='Pregunta',
        ),
    ]
