# Generated by Django 3.1 on 2021-08-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_auto_20210802_0407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pregunta',
            new_name='Preguntas',
        ),
    ]
