# Generated by Django 3.1 on 2021-07-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consejos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conTit', models.CharField(max_length=40)),
                ('conDes', models.TextField()),
                ('conImaUrl', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='enfermedad',
            options={'verbose_name_plural': 'Enfermedades'},
        ),
    ]
