# Generated by Django 3.1 on 2021-07-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedades', '0002_auto_20210711_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=200)),
                ('imagenP', models.ImageField(upload_to='img/doctores')),
                ('centroP', models.CharField(max_length=200)),
                ('celularP', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Personales',
            },
        ),
        migrations.AlterModelOptions(
            name='consejos',
            options={'verbose_name_plural': 'Consejos'},
        ),
    ]
