# Generated by Django 3.1 on 2021-07-11 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedades', '0003_auto_20210711_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalm',
            options={'verbose_name_plural': 'Personal Medico'},
        ),
    ]
