# Generated by Django 3.1 on 2021-07-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedades', '0004_auto_20210711_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedad',
            name='descripcionE',
            field=models.TextField(),
        ),
    ]
