# Generated by Django 3.1 on 2021-07-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedades', '0005_auto_20210711_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermedad',
            name='estrategia',
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='imagenSIN',
            field=models.ImageField(default='img/enfermedades/cerebro_duDVBew.png', upload_to='img/enfermedades/sintomas'),
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='sintoma1',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='sintoma2',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='sintoma3',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='sintoma4',
            field=models.TextField(default=' '),
        ),
    ]
