# Generated by Django 3.1 on 2021-07-29 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedades', '0006_auto_20210728_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermedad',
            name='imagenEF',
        ),
    ]
