# Generated by Django 3.1 on 2021-08-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedades', '0007_remove_enfermedad_imagenef'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalm',
            name='especialidadP',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='personalm',
            name='horarioP',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
