# Generated by Django 3.1 on 2021-08-02 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedades', '0008_auto_20210801_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consejos',
            name='conDes',
            field=models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='nombreE',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='sintoma1',
            field=models.TextField(max_length=150, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='sintoma2',
            field=models.TextField(max_length=150, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='sintoma3',
            field=models.TextField(max_length=150, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='sintoma4',
            field=models.TextField(max_length=150, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
    ]
